apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway-handler-30075
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/gateway-handler-30075
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
